language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
matrix:
  allow_failures:
    - rvm: 2.0.0
env: CAPYBARA_WAIT_TIME=30
before_script:
  - curl https://gist.github.com/robyoung/5862004/raw/sauce_connect_setup.sh | bash
script:
  - bundle exec rake test:all --trace
  - GOVUK_ASSET_HOST='https://static.production.alphagov.co.uk' BROWSER="windows xp,firefox" SAUCE_USER_NAME=$SAUCE_USERNAME SAUCE_API_KEY=$SAUCE_ACCESS_KEY bundle exec cucumber -p sauce
addons:
  sauce_connect:
    username: "jabley"
    access_key:
      secure: "DQb43L+GqdGcRpzEI6IF/dA9r7tRciCFf9zpqlIXWC77rKu+PiZYHmbacGSm4gYOGeLP5Iy3puyNn4ty84B38QJBNJRoDjtL/LBasBr4U0/dA9ueQ23PhWd3bLlMtn7WkD2PNNs2YNnpgz9kR1WKL3qe477M29T1xVgnTSuuUy0="
