language: ruby
rvm:
  - 1.9.3
  - 2.0.0
matrix:
  allow_failures:
    - rvm: 2.0.0
env:
  global:
    - secure: "SPkvVOl32mVTKB0cYA3zXtyksQcKmb4hDI6wPSzqxKVy+Ugv+vsR/x7wUd6ilMEKekFBbOsXysnWrHRfBevm6j9zh5TA40BZhReNFHI2h0sNlZjklqolQY/mEP82dYKHKYeH/McG3bQU+NdTo0UFl6v6CGVMF/V4qRR895GLTLw="
    - secure: "cMatu5jn1qabWT8qaoAk2qHrzmWyrmxkUW3XUrLeKLLgfuFN6uOkOz/JXdbVEV1AOCgwlwaDDruZkWhBjeKJO73+biM/gHK7cOOuqY5XIEnBfiGIGUR53aaMNjmjHlRSH1MlkwVGtrmrRmw9XNjXsmCsfBIOdkOVYIkzbe8buGw="
    - RUN_SERVER=true
    - APP_HOST='http://127.0.0.1:49221'
    - CAPYBARA_WAIT_TIME=30
before_script:
  - if [ $TRAVIS_BRANCH = "master" ] ; then curl https://gist.github.com/abersager/6521086/raw/sauce_connect_setup.sh | bash ; fi
script:
  - bundle exec rake test:all --trace
  - if [ $TRAVIS_BRANCH = "master" ] ; then bundle exec rake sauce:cucumber ; fi
notifications:
  email: false
